AWSTemplateFormatVersion: '2010-09-09'
Description: 'Polaris unified deployment (root stack) using nested stacks: Frontend (Amplify) + Backend (ECS Fargate + ALB)'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: ['development', 'staging', 'production']

  RepositoryUrl:
    Type: String
    Default: 'https://github.com/umair2602/polaris-rfp.git'

  BranchName:
    Type: String
    Default: main

  # Frontend (Amplify)
  GitHubToken:
    Type: String
    NoEcho: true

  EnableCustomDomain:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']

  CustomDomainName:
    Type: String
    Default: 'polariseco.com'

  CustomDomainPrefix:
    Type: String
    Default: 'rfp'

  FrontendBaseUrl:
    Type: String
    Description: Frontend base URL for backend CORS + OAuth (use custom domain URL when available)
    Default: 'https://rfp.polariseco.com'

  MagicLinkFromEmail:
    Type: String
    Description: SES-verified From address used for Cognito magic links
    Default: 'support@righteousgambit.com'

  # Backend (ECS + ALB)
  BackendApiDomainName:
    Type: String
    Default: 'api.rfp.polariseco.com'

  Route53HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for polariseco.com (e.g. Z123...)
    Default: 'Z0175396CVZ5P50IACQB'

  BackendImageUri:
    Type: String
    Description: ECR image URI for backend (including tag)

  CanvaClientId:
    Type: String
    Default: ''

  CanvaClientSecret:
    Type: String
    NoEcho: true
    Default: ''

  CanvaRedirectUri:
    Type: String
    Default: ''

  CanvaTokenEncKey:
    Type: String
    NoEcho: true
    Default: ''

  # Data store (DynamoDB)
  DdbTableName:
    Type: String
    Default: ''

  JwtSecret:
    Type: String
    NoEcho: true
    Default: ''

  JwtExpire:
    Type: String
    Default: '24h'

  OpenAiApiKeySecretArn:
    Type: String
    Description: Secrets Manager secret ARN for OPENAI_API_KEY (optional)
    Default: 'arn:aws:secretsmanager:us-east-1:211125621822:secret:openai-TbIvAk'

  OpenAiApiKeySecretJsonKey:
    Type: String
    Description: Optional JSON key name if the OpenAI secret is stored as JSON (e.g. OPENAI_API_KEY)
    Default: ''

  OpenAiModel:
    Type: String
    Description: OpenAI model to use by default (e.g. gpt-5.2)
    Default: 'gpt-5.2'

Conditions:
  UseCustomDomain: !Equals [!Ref EnableCustomDomain, 'true']
  UseProvidedCanvaClientId: !Not [!Equals [!Ref CanvaClientId, '']]
  UseProvidedCanvaClientSecret: !Not [!Equals [!Ref CanvaClientSecret, '']]
  UseProvidedCanvaRedirectUri: !Not [!Equals [!Ref CanvaRedirectUri, '']]
  UseProvidedCanvaTokenEncKey: !Not [!Equals [!Ref CanvaTokenEncKey, '']]
  UseProvidedDdbTableName: !Not [!Equals [!Ref DdbTableName, '']]
  UseProvidedJwtSecret: !Not [!Equals [!Ref JwtSecret, '']]

Resources:
  AuthStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: auth-cognito.yml
      Parameters:
        Environment: !Ref Environment
        FrontendBaseUrl: !Ref FrontendBaseUrl
        MagicLinkFromEmail: !Ref MagicLinkFromEmail

  PolarisJwtSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: !Sub 'JWT secret for Polaris backend (${Environment})'
      GenerateSecretString:
        PasswordLength: 64
        ExcludePunctuation: true

  PolarisDataTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  PolarisAssetsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          # Clean up orphan uploads (uploads done before a member is saved)
          - Id: ExpireUnassignedTeamUploads
            Status: Enabled
            Prefix: team/unassigned/
            ExpirationInDays: 7
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - HEAD
            AllowedHeaders:
              - '*'
            ExposedHeaders:
              - ETag
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: network-vpc.yml
      Parameters:
        Environment: !Ref Environment

  BackendStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: backend-ecs-alb.yml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        # Nested stack parameters must be strings; list parameters accept comma-delimited strings.
        PublicSubnetIds: !GetAtt NetworkStack.Outputs.PublicSubnetIds
        PrivateSubnetIds: !GetAtt NetworkStack.Outputs.PrivateSubnetIds
        BackendApiDomainName: !Ref BackendApiDomainName
        Route53HostedZoneId: !Ref Route53HostedZoneId
        ImageUri: !Ref BackendImageUri
        FrontendBaseUrl: !Ref FrontendBaseUrl
        CognitoUserPoolId: !GetAtt AuthStack.Outputs.UserPoolId
        CognitoClientId: !GetAtt AuthStack.Outputs.UserPoolClientId
        CognitoRegion: !Ref AWS::Region
        MagicLinkSessionsTableName: !GetAtt AuthStack.Outputs.MagicLinkSessionsTableName
        CanvaClientId: !If
          - UseProvidedCanvaClientId
          - !Ref CanvaClientId
          - '{{resolve:secretsmanager:polaris-rfp/canva:SecretString:CANVA_CLIENT_ID}}'
        CanvaClientSecret: !If
          - UseProvidedCanvaClientSecret
          - !Ref CanvaClientSecret
          - '{{resolve:secretsmanager:polaris-rfp/canva:SecretString:CANVA_CLIENT_SECRET}}'
        CanvaRedirectUri: !If
          - UseProvidedCanvaRedirectUri
          - !Ref CanvaRedirectUri
          - '{{resolve:secretsmanager:polaris-rfp/canva:SecretString:CANVA_REDIRECT_URI}}'
        CanvaTokenEncKey: !If
          - UseProvidedCanvaTokenEncKey
          - !Ref CanvaTokenEncKey
          - '{{resolve:secretsmanager:polaris-rfp/canva:SecretString:CANVA_TOKEN_ENC_KEY}}'
        DdbTableName: !Ref PolarisDataTable
        AssetsBucketName: !Ref PolarisAssetsBucket
        JwtSecret: !If
          - UseProvidedJwtSecret
          - !Ref JwtSecret
          - ''
        JwtSecretArn: !Ref PolarisJwtSecret
        JwtExpire: !Ref JwtExpire
        OpenAiApiKeySecretArn: !Ref OpenAiApiKeySecretArn
        OpenAiApiKeySecretJsonKey: !Ref OpenAiApiKeySecretJsonKey
        OpenAiModel: !Ref OpenAiModel

  FrontendStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: frontend-amplify.yml
      Parameters:
        RepositoryUrl: !Ref RepositoryUrl
        BranchName: !Ref BranchName
        Environment: !Ref Environment
        GitHubToken: !Ref GitHubToken
        BackendUrl: !GetAtt BackendStack.Outputs.BackendUrl
        CognitoUserPoolId: !GetAtt AuthStack.Outputs.UserPoolId
        CognitoClientId: !GetAtt AuthStack.Outputs.UserPoolClientId
        CognitoRegion: !Ref AWS::Region
        EnableCustomDomain: !Ref EnableCustomDomain
        CustomDomainName: !Ref CustomDomainName
        CustomDomainPrefix: !Ref CustomDomainPrefix

Outputs:
  CognitoUserPoolId:
    Description: Cognito user pool id
    Value: !GetAtt AuthStack.Outputs.UserPoolId

  CognitoUserPoolClientId:
    Description: Cognito app client id
    Value: !GetAtt AuthStack.Outputs.UserPoolClientId

  DdbTableName:
    Description: DynamoDB table name
    Value: !Ref PolarisDataTable

  AssetsBucketName:
    Description: S3 bucket name for uploaded assets (team headshots, etc.)
    Value: !Ref PolarisAssetsBucket

  BackendUrl:
    Description: Backend API URL
    Value: !GetAtt BackendStack.Outputs.BackendUrl

  BackendAlbDnsName:
    Description: Backend ALB DNS name
    Value: !GetAtt BackendStack.Outputs.LoadBalancerDnsName

  AmplifyAppId:
    Description: Amplify App ID
    Value: !GetAtt FrontendStack.Outputs.AmplifyAppId

  AmplifyDefaultUrl:
    Description: Amplify default URL for this branch
    Value: !GetAtt FrontendStack.Outputs.AmplifyAppUrl

  FrontendCustomDomainUrl:
    Description: Custom domain URL (if enabled)
    Value: !If
      - UseCustomDomain
      - !Sub 'https://${CustomDomainPrefix}.${CustomDomainName}'
      - ''

  Route53HostedZoneId:
    Description: Route53 hosted zone id used for backend domain
    Value: !Ref Route53HostedZoneId
